{% set name = "solar-data-tools-test" %}
{% set platform = 'linux' if linux else 'osx' if osx else 'win' %}
{%
  set cvxpy_builds = {
    'osx': {
      36: 'py36h02fde04_1',
      37: 'py37h622575a_1',
      38: 'py38h57202bd_1',
    },
    'linux': {
      36: 'py36hbb8311d_1',
      37: 'py37hf8c3989_1',
      38: 'py38hfe926b7_1',
    }
  }
%}


package:
  name: "{{ name|lower }}"
  version: {{ environ.get('VERSION_FROM_GIT_TAG') }}

source:
  git_url: https://github.com/derins/test-sdt

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - scipy
    - numpy >=1.16
    - pandas
    - seaborn
    - requests
    - pvlib-python 0.8.1 {{ cvxpy_builds[platform][py] }}
    - cvxpy 1.1.15 {{ cvxpy_builds[platform][py] }}

  run:
    - python
    - scipy
    - numpy >=1.16
    - pandas
    - seaborn
    - requests
    - scikit-learn
    - pvlib-python 0.8.1 {{ cvxpy_builds[platform][py] }}
    - cvxpy 1.1.15 {{ cvxpy_builds[platform][py] }}

about:
  home:
  license: BSD
  license_family: BSD
  license_file:
  summary: Tools for performing common tasks on solar PV data signals
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - bmeyers
    - derins
